export const FETCH_PEOPLE_SUCCESS = "FETCH_PEOPLE_SUCCESS";
export const PEOPLE_HAS_ERROR = "PEOPLE_HAVE_ERROR";
export const PEOPLE_ARE_LOADING = "PEOPLE_ARE_LOADING";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
export const RESET_STORE = "RESET_STORE";
