export const FETCH_STARSHIPS_SUCCESS = "FETCH_STARSHIPS_SUCCESS";
export const STARSHIPS_HAS_ERROR = "DATA_HAVE_ERROR";
export const STARSHIPS_ARE_LOADING = "STARSHIPS_ARE_LOADING";
export const FILTER_STARSHIPS = "FILTER_STARSHIPS";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
